### ISSUE TITLE
Error attaching 

### ISSUE THREAD

**Issue by criss20ster** [stijnwop/manualAttach#137]
I'm having trouble detaching the kemper tool from the lacote as you can see in the video  

https://www.youtube.com/watch?v=Sv4YiBy96pc

**Comment by KITT3000** [comment]
Since the beginning of this mod (FS15), all attachments and headers are connected from the vehicle, it is supposed to imitate realistic connection where such tools are first "hung" by the vehicle's conveyor and only then you manually block the locks and connect the hoses and PTO. So in FS you have to atttach the attachment in the vehicle and deattach it also while in the vehicle.
