### ISSUE TITLE
[BUG] ITRunner MOD works without PTO attached

### ISSUE THREAD

**Issue by turbostar190** [stijnwop/manualAttach#39]
**Describe the bug**
ITRunner mod arm works also without PTO attached

**To Reproduce**
1. Buy ITRunner
2. Attach to a tractor without attaching PTO
3. You will see "extend the arm"

**Expected behavior**
Arm should move only with PTO attached to the tractor?

**Desktop (please complete the following information):**
 - OS: Windows 10 1803
 - FS patch version 1.3.0.1 Steam

**Comment by stijnwop** [comment]
Yeah, well for most machines folding is hydraulic based. That's also where the current logic is based on.

So: without hydraulics it means that you won´t be able to unfold (or extend the arm in this case), but since that IT runner does not have hydraulics it will just function.

Not sure if this is a bug at all or if this is something I want to make PTO dependent too.

**Comment by stijnwop** [comment]
Same here? @turbostar190

**Comment by turbostar190** [comment]
I think it's better to leave it like now. I agree with you; if hoses are missing, it will just work.
