### ISSUE TITLE
Issue between CaseIH 1660 and the Case IH Corn Cutter

### ISSUE THREAD

**Issue by johnny86se** [stijnwop/manualAttach#61]
It seems to be an issue  to connect the PTO between the Case IH 1660 and the Case IH Corn cutter from Matt26 on modhub. It seems like the Case IH 1660 cant connect to any PTO's from the corn headers but from the usual headers. Just thinking if its a manualAttach bug.

**Comment by KITT3000** [comment]
I analyzed this problem and it turned out that `ptoName` is to blame. The header uses the name `LEFT_PTO` and `LEFT_PTO`, while in the Giants combine (Case IH 1660) it did not add this attribute at all, so the PTO script assigns the name `DEFAULT_PTO`, and since the names do not match, you cannot connect PTO. There is no problem with the combine e.g. Rostelmash Nova 330.
