### ISSUE TITLE
Interferes with water tap triggers.

### ISSUE THREAD

**Issue by EddieGrouch** [stijnwop/manualAttach#91]
On the Hof Bergmann 1.0.0.7 map there are water taps that are triggered when a hand water bucket is placed under them.  These taps do not use hoses.  With MA mod active these triggers are ignored. No errors are given at the time.

Tested on water taps located in the sink of the farm bakery and the on the side of the chicken house.

**Comment by KITT3000** [comment]
You need to make a new vehicleType for these buckets because the current one they use is also useful for other objects (probably some silos) and remove unnecessary soechalizations through which MA activates

**Comment by Nisfeer** [comment]
How do you do that? I'd like as well version compatible with Hof Bergmann map, thanks.

**Comment by KITT3000** [comment]
@Nisfeer Find a vehicle type as below and set only the following specializations:
```xml
<type name="mapStorageSilos" className="Vehicle" filename="$dataS/scripts/vehicles/Vehicle.lua">
			<specialization name="animatedVehicle" />
			<specialization name="fillUnit" />
			<specialization name="fillVolume" />
			<specialization name="dischargeable" />
			<specialization name="fillTriggerVehicle" />
			<specialization name="fillTypeSigns" />
			<specialization name="manureSystemVehicle"/>
		</type>
		```

**Comment by Nisfeer** [comment]
What will be destroyed in-game and what happens to save game if I remove rest of specializations from the map?

**Comment by KITT3000** [comment]
Nothing, these specializations are not used in objects that have this vehicleType, only the script from MA checks when loading the game if there are these specializations and if so, it adds its functions.

**Comment by Nisfeer** [comment]
I can't really understand what specializations are for could you give an ex. so I can understand why author of the map put them in this specific "type"? I don't really get what StorageSilos got to do with for ex. wheels, dashboard, lights and washable specializations.

I also found this at their FAQ:
Why I can't get water with bucket?
That's only known in combination with manualAttach. To use manualAttach at HofBergmann it is necessary to use the following prerelease from manualAttach: https://github.com/stijnwop/manualAttach/releases/download/2.0.1.1/FS19_ManualAttach.zip

I tested it and it works with this pre-release but I'd like to use this MA 1.1.0.0 updated version instead.

I'm just trying to understand why they keep it and tell players to use pre-release instead of telling them "Hey, you can delete these lines from moddesc and it will work fine." sorry for the questions I'm just curious how specializations works, why it stopped working with an updated MA version and why everything is fine even if I delete these lines?

I still didn't check it but the water and milk should pour down through the tap triggers right now so thank you once again.

**Comment by KITT3000** [comment]
What FAQ? The author of the map added a lot of specializations because he obviously doesn't understand what they are for, he only uses a few of them, but he pasted the others unnecessarily. Since this version MA (which you provided) has changed the way of registering its specializations (and detecting required ones) in other mods and additionally there have been a lot of improvements, so using the old version is not recommended.
